export const POLL_LIST_LOADING = 'POLL_LIST_LOADING';
export const POLL_LIST_LOADING_FINISH = 'POLL_LIST_LOADING_FINISH';
export const CURRENT_POLL_LIST_LOADING = 'CURRENT_POLL_LIST_LOADING';
export const CURRENT_POLL_LIST_LOADING_FINISH = 'CURRENT_POLL_LIST_LOADING';
export const POLL_DATA_FETCHED = 'POLL_DATA_FETCHED';
export const POLL_CREATED = 'POLL_CREATED';