version: "3.8"

services:
  poll-voting-ui:
    build: ./poll-voting-ui
    image: poll-voting-ui:latest
    environment:
      REACT_APP_BACKEND_URL: example
      REACT_APP_POLL_RESULT_URL: http://poll-voting-result-ui:3001
    ports:
      - 3000:80
    networks:
      - poll

  poll-voting-result-ui:
    build: ./poll-voting-result-ui
    image: poll-voting-result-ui:latest
    ports:
      - 3001:80
    networks:
      - poll

  poll-voting-service:
    build: ./poll-voting-service
    image: poll-voting-service:latest
    environment:
      MONGO_URL: mongodb://mongo:27017/vote
      PORT: 5000
    ports:
      - 5000:5000
    networks:
      - poll

  poll-voting-result-service:
    build: ./poll-voting-result-service
    image: poll-voting-result-service:latest
    environment:
      MONGO_URL: mongodb://mongo:27017/vote
      POLL_VOTING_SERVICE: http://poll-voting-service:5000
      PORT: 5001
    ports:
      - 5001:5001
    networks:
      - poll

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - my_network

networks:
  poll:
    driver: bridge
