apiVersion: v1
kind: Service
metadata:
  name: mongo-service-primary
  namespace: poll
spec:
  clusterIP: None
  selector:
    role: mongo-primary
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: poll-statefulset-primary
  namespace: poll
spec:
  selector:
    matchLabels:
      role: mongo-primary
  serviceName: mongo-service-primary
  replicas: 2
  template:
    metadata:
      namespace: poll
      name: mongo
      labels:
        role: mongo-primary
    spec:
      initContainers:
        - name: mongo-replica-files-copy
          image: busybox:latest
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: temp-mongo-config
              mountPath: /tmp/rs-scripts
            - name: mongo-config
              mountPath: /rs-scripts
          command: ["sh","-c" , "cp -r /tmp/rs-scripts/* /rs-scripts/ && chmod +x /rs-scripts/*"]
      containers:
      - name: mongo
        image: mongo
        command: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "poll_rs" ]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
        - name: temp-mongo-config
          mountPath: /tmp/rs-scripts
        - name: mongo-config
          mountPath: /rs-scripts
      restartPolicy: Always
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: poll-pvc
        - name: temp-mongo-config
          configMap:
            name: mongo-replica-config
        - name: mongo-config
          emptyDir: {}
