apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-replica-config-init
  namespace: poll
data: 
    init.js: |
      rs.status();
      db.createUser({user: 'admin', pwd: 'admin', roles: [ { role: 'root', db: 'admin' } ]});


