apiVersion: v1
kind: PersistentVolume
metadata:
  name: poll-pv
  namespace: poll
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/suraj