apiVersion: v1
kind: Service
metadata:
  name: poll-voting-ui-service
  namespace: poll-namespace
spec:
  type: NodePort
  selector:
    app: poll-voting-ui
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-voting-ui
  namespace: poll-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-voting-ui
  template:
    metadata:
      namespace: poll-namespace
      labels:
        app: poll-voting-ui
    spec:
      containers:
      - name: poll-voting-ui
        image: suraj49470/poll-voting-ui:latest
        env :
          - name:  REACT_APP_BACKEND_URL
            value: http://poll-voting-service:5000 
          - name:  REACT_APP_POLL_RESULT_URL
            value: http://poll-voting-result-ui-service:3001 
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      # volumes:
      #   - name: poll-pod-volume
      #     PersistentVolumeClaim:
      #       claimName: poll-pvc
