apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poll-pvc
  namespace: poll
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
