apiVersion: v1
kind: PersistentVolume
metadata:
  name: poll-pv
  namespace: poll
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: poll-storage-class
  hostPath:
    path: /mnt/data
