apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poll-pvc
  namespace: poll
spec:
  storageClassName: standard
  volumeName: poll-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
