apiVersion: v1
kind: Service
metadata:
  name: poll-voting-result-service
  namespace: poll-namespace
spec:
  type: ClusterIP
  selector:
    app: poll-voting-result-service
  ports:
  - port: 5001
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-voting-result-service
  namespace: poll-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-voting-result-service
  template:
    metadata:
      namespace: poll-namespace
      labels:
        app: poll-voting-result-service
    spec:
      containers:
      - name: poll-voting-result-service
        image: suraj49470/poll-voting-result-service:latest
        env:
          - name: PORT
            value: "80"
          - name: POLL_VOTING_SERVICE
            value: http://poll-voting-service:5000
          - name: MONGO_URL
            value: TBD
        resources:
          limits:
            memory: "250Mi"
            cpu: "750m"
        ports:
        - containerPort: 80
      # volumes:
      #   - name: poll-pod-volume
      #     PersistentVolumeClaim:
      #       claimName: poll-pvc
