apiVersion: v1
kind: ConfigMap
metadata:
  name: transform-config
  namespace: poll
data: 
  transform.sh : |
    #!/bin/sh
    printenv
    cd /usr/share/nginx/html/static/js
    # Iterate over all .js files in the current directory
    for filename in *.js; do
        echo "$filename";
        echo $REACT_APP_BACKEND_URL;
        echo $REACT_APP_POLL_RESULT_URL;
        sed -i "s|%REACT_APP_BACKEND_URL%|$REACT_APP_BACKEND_URL|g" "$filename";
        sed -i "s|%REACT_APP_POLL_RESULT_URL%|$REACT_APP_POLL_RESULT_URL|g" "$filename";
        sed -i "s|%REACT_APP_HOSTNAME%|$HOSTNAME|g" "$filename"
    done

