version: '3.8'

services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    command: ["bash", "-c", "chmod +x /initiate_replica_set.sh && /initiate_replica_set.sh"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo1/data:/data/db
      - ./initiate_replica_set.sh:/initiate_replica_set.sh
    networks:
      - mongo-net
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--port", "27017"]
    ports:
      - "27018:27017"
    volumes:
      - ./mongo2/data:/data/db
    networks:
      - mongo-net

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--port", "27017"]
    ports:
      - "27019:27017"
    volumes:
      - ./mongo3/data:/data/db
    networks:
      - mongo-net

networks:
  mongo-net:
