FROM node:18-alpine3.18 as Build
WORKDIR /poll-voting-ui
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build
RUN chmod +x /usr/src/app/entrypoint.sh
RUN ./entrypoint.sh

FROM  nginx:1.25.5-alpine-slim as deploy
COPY --from=Build /poll-voting-ui/build /usr/share/nginx/html
EXPOSE 80
